services:
  - type: web
    name: ukb-app-00
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python nhanes_cox_app/app.py
    envVars:
      PYTHON_VERSION: 3.10.14
